### ISSUE TITLE
DE/RE not working

### ISSUE THREAD

**Issue by ffeldbauer** [Sillern/BB-RS485#1]
Hey,

I wanted to use RS485 on my BeagleBone Black and found your Device Tree Overlay.
So I cloned the repo, compiled the DTS and loaded the overlay....
Receiving data over the RS485 interface works fine, but I cannot send data.
GPIO3[19] stays low.....

I'm using the debian 8.2 console image with kernel 4.1.
The overlay is loaded with `echo BB-RS485 > /sys/devices/platform/bone_capemgr/slots`
Receiving data was tested via `cat /dev/ttyO4`
Sending data via `echo "test" > /dev/ttyO4`

Any idea why DE/RE selection does not work? Did I miss anything?

**Comment by Sillern** [comment]
Hello, 

I don't have access to my beaglebone at the moment, I'll try to check later.
If I remember correctly it has something to do with RTS not being enabled.

Some more information is here: https://gist.github.com/alexanderhiam/65817fcf590ae77c7ff0

**Comment by ffeldbauer** [comment]
Hey,
ok...I thought RTS is enabled through the device tree!?
I tried the python script, but it is also not working for me. I get the error message:

Traceback (most recent call last):
  File "rs485-ioctl.py", line 47, in <module>
    fcntl.ioctl(fd, TIOCSRS485, serial_rs485)
IOError: [Errno 25] Inappropriate ioctl for device

**Comment by ffeldbauer** [comment]
Ok...another question concerning this matter: I'm running kernel version "4.1.12-ti-r28"
I get the feeling this version is missing the patch to use a GPIO for RE/DE...
Is this correct? Can you point me to a recent kernel version including this patch?

**Comment by Sillern** [comment]
I haven't got around to checking my bbb yet.

Did you run that script with root privileges btw?

4.1.12 should be ok, if you have the linux-headers installed, you can check include/uapi/linux/serial.h

From http://inspire.logicsupply.com/2014/09/beaglebone-rs-485-communication.html:
Note: The RS-485 mode was a fairly recent addition to the omap-serial Kernel driver, so to ensure that you have the correct driver you should be running a Debian image with a recent 3.8 Kernel. You can grab the latest Debian image from beagleboard.org/latest-images. You can check your Kernel build version with # uname -r; if you see 3.8.13-bone39 or higher you should have the correct version of the serial driver with RS-485 support.

**Comment by ffeldbauer** [comment]
If checked the /usr/src/linux-headers-4.1.10-ti-r21/include/uapi/linux/serial.h
and it defines the struct

struct serial_rs485 {
        __u32   flags;                  /\* RS485 feature flags _/
#define SER_RS485_ENABLED               (1 << 0)        /_ If enabled _/
#define SER_RS485_RTS_ON_SEND           (1 << 1)        /_ Logical level for
                                                           RTS pin when
                                                           sending _/
#define SER_RS485_RTS_AFTER_SEND        (1 << 2)        /_ Logical level for
                                                           RTS pin after sent_/
#define SER_RS485_RX_DURING_TX          (1 << 4)
        __u32   delay_rts_before_send;  /_ Delay before send (milliseconds) _/
        __u32   delay_rts_after_send;   /_ Delay after send (milliseconds) _/
        __u32   padding[5];             /_ Memory is cheap, new structs
                                           are a royal PITA .. */
};

So, according to the link you provided, it really seems, this kernel version does not support using a GPIO as RE/DE

**Comment by ffeldbauer** [comment]
Ok....I just see I made a mistake two posts earlier...I'm running 4.1.10-ti-r21...
And yes, I tried to execute the python script as root. Same result as for the normal user...

**Comment by Sillern** [comment]
The patch seems to be here: 
https://github.com/beagleboard/linux/blob/3.8.13-bone71-lsm303/include/uapi/linux/serial.h
but not in later branches:
https://github.com/beagleboard/linux/blob/master/include/uapi/linux/serial.h

**Comment by Sillern** [comment]
It seems that later kernel have changed the procedure regarding the GPIO port setting.
See here: https://github.com/beagleboard/linux/blob/master/drivers/tty/serial/omap-serial.c#L1569

**Comment by Sillern** [comment]
You can try use this version. I'm not sure of its validity though.
https://github.com/Sillern/BB-RS485/pull/2

**Comment by ffeldbauer** [comment]
I already tested this additional flag with no succes... I also found that for newer versions you have to use "target=<&uart4>"  in the fragment when using UART4

**Comment by ffeldbauer** [comment]
Ok. So I now verified, that for the newer kernel versions, you have to use "target=<&uart4>" instead of uart5. Otherwise ttyO5 will be created...
https://github.com/Sillern/BB-RS485/blob/Sillern-patch-1/BB-RS485-00A0.dts#L34

**Comment by Sillern** [comment]
Great, I'll update and merge into master.

**Comment by ffeldbauer** [comment]
There seems to be still a problem...neither with python nor with C++ I can use the RS485 port.
The error message is "inappropriate ioctl for device"....
I'm currently testing this on the Debian Jessie console image from 2015-11-08

**Comment by ffeldbauer** [comment]
Ok....after several hours search I found the reason for the problem:
"The 4.x-series ti kernels use the omap8250 driver which does not
have RS485 support (yet)."
From the beaglebone googlegroups  http://beagleboard.org/Community/Forums

**Comment by TybiBeaton** [comment]
Actually the RS-485 mode was a fairly recent addition to the omap-serial Kernel driver, so to ensure that you have the correct driver you should be running a Debian image with a recent 3.8 Kernel.
 You can grab the latest Debian image from beagleboard.org/latest-images. You can check your Kernel build version with # uname -r; if you see 3.8.13-bone39 or higher you should have the correct version of the serial driver.

<a href=http://www.7pcb.com/PCB-Assembly-Service.php>circuit board assembly</a>
